select GENERAL_1, GENERAL_2, GENERAL_3, GENERAL_4, GENERAL_5, GENERAL_6, GENERAL_7, GENERAL_8, GENERAL_9, GENERAL_10 
from SV_BUS.PRODUCT_INSTANCE_HISTORY 
where BASE_PRODUCT_INSTANCE_ID IS NOT NULL --COMP-PROD
--and GENERAL_1 = '63923704'
--and GENERAL_5 <> '10'

select GENERAL_1, GENERAL_2, GENERAL_3, GENERAL_4, GENERAL_5, GENERAL_6, GENERAL_7, GENERAL_8, GENERAL_9, GENERAL_10 from SV_BUS.PRODUCT_INSTANCE_HISTORY
where BASE_PRODUCT_INSTANCE_ID IS NULL --BASE-PROD 


select GENERAL_1, GENERAL_2, GENERAL_3, GENERAL_4, GENERAL_5, GENERAL_6, GENERAL_7, GENERAL_8, GENERAL_9, GENERAL_10, INDUSTRY_GENERAL_1, INDUSTRY_GENERAL_2, INDUSTRY_GENERAL_3, INDUSTRY_GENERAL_4, INDUSTRY_GENERAL_5, 
INDUSTRY_GENERAL_6, INDUSTRY_GENERAL_7, INDUSTRY_GENERAL_8, INDUSTRY_GENERAL_9, INDUSTRY_GENERAL_10 from SV_BUS.SERVICE_HISTORY