-- NORMALISED EVENT ERROR -----------------------------------------------------
SELECT 
      NEE.NORMALISED_EVENT_ID,
      NEE.LAST_MODIFIED,
      DECODE(NEE.NORMALISED_EVENT_TYPE_ID,4100003,25000080,25000080) as NORMALISED_EVENT_TYPE_ID,
      NEE.PARENT_NORMALISED_EVENT_ID,
      NEE.NORMALISED_EVENT_FILE_ID,
      NEE.FILE_RECORD_NR,
      NEE.EXTERNAL_FILE_RECORD_NR,
      NEE.ORIGINAL_FILE_ID,
      NEE.ORIGINAL_FILE_RECORD_NR,
      NEE.REPROCESSED_COUNT,
      NEE.ERROR_MESSAGE_ID,
      NEE.ERROR_MESSAGE,
      NEE.ERROR_CLASS_CODE,
      NEE.REPROCESSED_FILE_ID,
      NEE.REPROCESSED_FILE_RECORD_NR,
      NEE.A_PARTY_ID,
      NEE.A_PARTY_NETWORK_ID,
      NEE.A_PARTY_NAME,
      NEE.A_PARTY_TON_CODE,
      NEE.A_PARTY_CELL_ID,
      NEE.A_PARTY_CARRIER_CODE,
      NEE.A_PARTY_LOCATION_CODE,
      NEE.A_PARTY_ROUTE,
      NEE.B_PARTY_ID,
      NEE.B_PARTY_NETWORK_ID,
      NEE.B_PARTY_NAME,
      NEE.B_PARTY_TON_CODE,
      NEE.B_PARTY_CELL_ID,
      NEE.B_PARTY_CARRIER_CODE,
      NEE.B_PARTY_LOCATION_CODE,
      NEE.B_PARTY_ROUTE,
      NEE.C_PARTY_ID,
      NEE.C_PARTY_NETWORK_ID,
      NEE.C_PARTY_NAME,
      NEE.C_PARTY_INTERNAL_ID,
      NEE.C_PARTY_TON_CODE,
      NEE.C_PARTY_CELL_ID,
      NEE.C_PARTY_CARRIER_CODE,
      NEE.C_PARTY_LOCATION_CODE,
      NEE.C_PARTY_ROUTE,
      NEE.FULL_PATH,
      NEE.CASCADE_CARRIER_CODE,
      NEE.SWITCH_START_DATE,
      NEE.CHARGE_START_DATE,
      NEE.PERIOD_START_DATE,
      NEE.PERIOD_END_DATE,
      NEE.EVENT_SOURCE,
      NEE.EVENT_CLASS_CODE,
      NEE.BILL_RUN_ID,
      NEE.ROOT_CUSTOMER_NODE_ID,
      NEE.EVENT_TYPE_CODE,
      NEE.EVENT_SUB_TYPE_CODE,
      NEE.DURATION,
      NEE.VOLUME,
      NEE.PULSES,
      NEE.CHARGE,
      NEE.CURRENCY_ID,
      NEE.RATE_BAND,
      NEE.GENERAL_1,
      NEE.GENERAL_2,
      NEE.GENERAL_3,
      NEE.GENERAL_4,
      NEE.GENERAL_5,
      NEE.GENERAL_6,
      NEE.GENERAL_7,
      NEE.GENERAL_8,
      NEE.GENERAL_9,
      NEE.GENERAL_10,
      NEE.GENERAL_11,
      NEE.GENERAL_12,
      NEE.GENERAL_13,
      NEE.GENERAL_14,
      NEE.GENERAL_15,
      NEE.GENERAL_16,
      NEE.GENERAL_17,
      NEE.GENERAL_18,
      NEE.GENERAL_19,
      NEE.GENERAL_20,
      NEE.PARTITION_NR,
      NEF.FILENAME
FROM NORMALISED_EVENT_ERROR NEE
JOIN NORMALISED_EVENT_FILE NEF ON NEE.NORMALISED_EVENT_FILE_ID=NEF.NORMALISED_EVENT_FILE_ID 
      AND (NEF.FILENAME LIKE 'SV9_EWSD_BUS_%' OR NEF.FILENAME LIKE 'SV9_IN_BUS_%') 
WHERE 1=1
--AND NEE.NORMALISED_EVENT_ID=1622373326

AND NEE.LAST_MODIFIED >= TO_DATE('01-10-2019 00:00:00','DD-MM-YYYY HH24:MI:SS')
AND ROWNUM <=5

select * from normalised_event_type --4100003
CREATE INDEX I_NORMALISED_ENT_ERR_A_PARTY 
ON NORMALISED_EVENT_ERROR(A_PARTY_ID,CHARGE_START_DATE)

CREATE INDEX I_ACCOUNT_CUSTOMER_GENERAL_2
ON ACCOUNT(CUSTOMER_NODE_ID,GENERAL_2)


-- NORMALISED EVENT TYPE -----------------------------------------------------
SELECT
    NORMALISED_EVENT_TYPE_ID,
    NORMALISED_EVENT_TYPE_NAME,
    DESCRIPTION,
    LAST_MODIFIED,
    ATLANTA_OPERATOR_ID,
    ATLANTA_GROUP_ID,
    ADMIN_ENTITY_VALIDATION_ID,
    CSR_ENTITY_VALIDATION_ID,
    CSR_SRCH_ENTITY_VALIDATION_ID,
    INV_ADMIN_ENTITY_VALIDATION_ID,
    INV_CSR_ENTITY_VALIDATION_ID,
    VERSION_STR
FROM NORMALISED_EVENT_TYPE

--RGP_NORMALISED_EVENT_A------------------------------------------------------

desc OPS$SV6DEV01.RGP_NORMALISED_EVENT_A
SELECT 
    RNE.BILL_RUN_ID,
    RNE.VOLUME,
    RNE.CHARGE,
    RNE.CURRENCY_ID,
    RNE.CUSTOMER_NODE_ID,
    RNE.C_PARTY_CARRIER_CODE,
    RNE.C_PARTY_CELL_ID,
    RNE.C_PARTY_LOCATION_CODE,
    RNE.C_PARTY_NAME,
    RNE.C_PARTY_ROUTE,
    RNE.C_PARTY_TON_CODE,
    RNE.DURATION,
    RNE.END_DAY_OF_MONTH,
    RNE.EQUIPMENT_ID,
    RNE.EVENT_SOURCE,
    RNE.EVENT_SUB_TYPE_CODE,
    RNE.EVENT_TYPE_CODE,
    RNE.FAC_GROUP_INSTANCE_ID,
    RNE.FULL_PATH,
    RNE.GENERAL_1,
    RNE.GENERAL_10,
    RNE.GENERAL_11,
    RNE.GENERAL_12,
    RNE.GENERAL_13,
    RNE.GENERAL_14,
    RNE.GENERAL_15,
    RNE.GENERAL_16,
    RNE.GENERAL_17,
    RNE.GENERAL_18,
    RNE.GENERAL_19,
    RNE.GENERAL_2,
    RNE.GENERAL_20,
    RNE.GENERAL_3,
    RNE.GENERAL_4,
    RNE.GENERAL_5,
    RNE.GENERAL_6,
    RNE.GENERAL_7,
    RNE.GENERAL_8,
    RNE.GENERAL_9,
    RNE.LAST_MODIFIED,
    RNE.NORMALISED_EVENT_TYPE_ID,
    RNE.PERIOD_END_DATE,
    RNE.PERIOD_START_DATE,
    RNE.PRODUCT_INSTANCE_ID,
    RNE.PULSES,
    RNE.QA_IND_CODE,
    RNE.RATE_BAND,
    RNE.RGP_FILE_ID,
    RNE.RGP_FILE_RECORD_NR,
    RNE.ROOT_CUSTOMER_NODE_ID,
    RNE.SERVICE_ID,
    RNE.STATUS_CODE,
    RNE.SWITCH_START_DATE,
    RNE.TARIFF_ID,
    RNE.VERSION_STR,
    RNE.CASCADE_CARRIER_CODE
FROM RGP_NORMALISED_EVENT_A RNE
JOIN ACCOUNT ACC ON RNE.CUSTOMER_NODE_ID=ACC.CUSTOMER_NODE_ID AND ACC.GENERAL_2 = 'CLARIFY'
WHERE 1=1


SELECT 
ENTRY_DATE, 
RGP_FILE_RECORD_NR,
PRODUCT_INSTANCE_ID
FROM H3ATT_DWH_RGP_NE_A_V


-- NORMALISED_EVENT_A----------------------------------------------------------

SELECT
      NEA.ENTRY_DATE,
      NEA.USERNAME,
      NEA.OPERATION_CODE,
      NEA.NORMALISED_EVENT_ID,
      NEA.LAST_MODIFIED,
      NEA.NORMALISED_EVENT_TYPE_ID,
      NEA.PARENT_NORMALISED_EVENT_ID,
      NEA.NORMALISED_EVENT_FILE_ID,
      NEA.FILE_RECORD_NR,
      NEA.EXTERNAL_FILE_RECORD_NR,
      NEA.ORIGINAL_FILE_ID,
      NEA.ORIGINAL_FILE_RECORD_NR,
      NEA.REPROCESSED_COUNT,
      NEA.A_PARTY_ID,
      NEA.A_PARTY_NETWORK_ID,
      NEA.A_PARTY_NAME,
      NEA.A_PARTY_TON_CODE,
      NEA.A_PARTY_CELL_ID,
      NEA.A_PARTY_CARRIER_CODE,
      NEA.A_PARTY_LOCATION_CODE,
      NEA.A_PARTY_ROUTE,
      NEA.B_PARTY_ID,
      NEA.B_PARTY_NETWORK_ID,
      NEA.B_PARTY_NAME,
      NEA.B_PARTY_TON_CODE,
      NEA.B_PARTY_CELL_ID,
      NEA.B_PARTY_CARRIER_CODE,
      NEA.B_PARTY_LOCATION_CODE,
      NEA.B_PARTY_ROUTE,
      NEA.C_PARTY_ID,
      NEA.C_PARTY_NETWORK_ID,
      NEA.C_PARTY_NAME,
      NEA.C_PARTY_INTERNAL_ID,
      NEA.C_PARTY_TON_CODE,
      NEA.C_PARTY_CELL_ID,
      NEA.C_PARTY_CARRIER_CODE,
      NEA.C_PARTY_LOCATION_CODE,
      NEA.C_PARTY_ROUTE,
      NEA.FULL_PATH,
      NEA.CASCADE_CARRIER_CODE,
      NEA.SWITCH_START_DATE,
      NEA.CHARGE_START_DATE,
      NEA.PERIOD_START_DATE,
      NEA.PERIOD_END_DATE,
      NEA.EVENT_SOURCE,
      NEA.EVENT_CLASS_CODE,
      NEA.BILL_RUN_ID,
      NEA.ROOT_CUSTOMER_NODE_ID,
      NEA.EVENT_TYPE_CODE,
      NEA.EVENT_SUB_TYPE_CODE,
      NEA.DURATION,
      NEA.VOLUME,
      NEA.PULSES,
      NEA.CHARGE,
      NEA.CURRENCY_ID,
      NEA.RATE_BAND,
      NEA.GENERAL_1,
      NEA.GENERAL_2,
      NEA.GENERAL_3,
      NEA.GENERAL_4,
      NEA.GENERAL_5,
      NEA.GENERAL_6,
      NEA.GENERAL_7,
      NEA.GENERAL_8,
      NEA.GENERAL_9,
      NEA.GENERAL_10,
      NEA.GENERAL_11,
      NEA.GENERAL_12,
      NEA.GENERAL_13,
      NEA.GENERAL_14,
      NEA.GENERAL_15,
      NEA.GENERAL_16,
      NEA.GENERAL_17,
      NEA.GENERAL_18,
      NEA.GENERAL_19,
      NEA.GENERAL_20,
      NEA.DUMMY,
      NEA.PARTITION_NR
FROM NORMALISED_EVENT_A NEA
JOIN SERVICE_HISTORY SH  ON NEA.A_PARTY_ID=SH.SERVICE_NAME  
JOIN ACCOUNT ACC ON SH.CUSTOMER_NODE_ID=ACC.CUSTOMER_NODE_ID AND ACC.GENERAL_2 = 'CLARIFY'
WHERE 1=1

SELECT 
ENTRY_DATE, 
NORMALISED_EVENT_ID,
CHARGE_START_DATE
FROM H3ATT_DWH_NORMALISED_EVENT_A_V


-------------------------------------------------------------------------------
select 
  LAST_MODIFIED,
  NORMALISED_EVENT_TYPE_ID,
  NORMALISED_EVENT_FILE_ID,
  REPROCESSED_FILE_ID,
  A_PARTY_ID,
  A_PARTY_ROUTE,
  B_PARTY_ID,
  C_PARTY_ID,
  CHARGE_START_DATE,
  EVENT_TYPE_CODE,
  EVENT_SUB_TYPE_CODE,
  DURATION,
  VOLUME,
  GENERAL_3,
  GENERAL_5
FROM
  NORMALISED_EVENT_ERROR 
WHERE GENERAL_5 IS NOT NULL


desc OPS$SV9DEV01.NORMALISED_EVENT_ERROR
