ALTER SESSION set NLS_DATE_FORMAT = 'DD-MM-YYYY HH24:MI:SS'
--------------------------------------------------------------------------------
--SERVICE_HISTORY
--------------------------------------------------------------------------------

--select count(unique(service_name)) from (
--select count(*) from ( --9685
select
--DWHSH.SERVICE_NAME,
DWHSH.GENERAL_1,
--DWHSH.GENERAL_4,
DWHSH.GENERAL_6,
DWHSH.INDUSTRY_GENERAL_1,
DWHSH.INDUSTRY_GENERAL_3 
from SV_BUS.SERVICE_HISTORY DWHSH
JOIN SV_BUS.ACCOUNT ACC ON DWHSH.CUSTOMER_NODE_ID = ACC.CUSTOMER_NODE_ID 
      AND ACCOUNT_NAME NOT IN (22643580,60086806,37052669,17837525,99398691)
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  ACC.ACCOUNT_NAME = to_char (HPEA.X_BILL_SITE_ID) 
      AND HPEA.TASK_QUEUE_ID=1001003390 
where 1=1 
and  DWHSH. EFFECTIVE_END_DATE > sysdate 
and DWHSH.SERVICE_STATUS_CODE not in (9)
and DWHSH. LAST_MODIFIED < TO_DATE('03-02-2020 00:00:00','DD-MM-YYYY HH24:MI:SS')
--AND DWHSH.SERVICE_TYPE_ID=25000005 --284880
--)

minus

--select count(*) from ( --8805
select
--SVSH.SERVICE_NAME,
SVSH.GENERAL_1,
--SVSH.GENERAL_4,
SVSH.GENERAL_6,
SVSH.INDUSTRY_GENERAL_1,
SVSH.INDUSTRY_GENERAL_3 
from SV_PROD.H3ATT_DWH_SERVICE_HISTORY_V@SV9PCT01.IT.INTERNAL SVSH
JOIN SV_PROD.ACCOUNT@SV9PCT01.IT.INTERNAL ACC ON SVSH.CUSTOMER_NODE_ID = ACC.CUSTOMER_NODE_ID 
      AND ACCOUNT_NAME NOT IN ('PBA22643580','PBA60086806','PBA37052669','PBA17837525','PBA99398691')
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  ACC.ACCOUNT_NAME = 'PBA'|| to_char (HPEA.X_BILL_SITE_ID) 
      AND HPEA.TASK_QUEUE_ID=1001003390
WHERE 1=1
--)

select count (*) from (select * from SV_PROD.H3ATT_DWH_SERVICE_HISTORY_V@SV9PCT01.IT.INTERNAL) --8805

--------------------------------------------------------------------------------
--PRODUCT_INSTANCE_HISTORY
--------------------------------------------------------------------------------
--select count(*) from (
SELECT
DPIH.GENERAL_1,
DPIH.GENERAL_2,
DPIH.GENERAL_3,
DPIH.GENERAL_4,
DPIH.GENERAL_5,
DPIH.GENERAL_6,
DPIH.GENERAL_7,
DPIH.GENERAL_8,
DPIH.GENERAL_9,
DPIH.GENERAL_10
FROM SV_BUS.PRODUCT_INSTANCE_HISTORY DPIH
JOIN SV_BUS.ACCOUNT ACC ON DPIH.CUSTOMER_NODE_ID = ACC.CUSTOMER_NODE_ID 
      AND ACCOUNT_NAME NOT IN (22643580,60086806,37052669,17837525,99398691)
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  ACC.ACCOUNT_NAME = to_char (HPEA.X_BILL_SITE_ID) 
      AND HPEA.TASK_QUEUE_ID=1001003390 
WHERE 1=1
AND DPIH.PRODUCT_INSTANCE_STATUS_CODE <> 9
AND DPIH.EFFECTIVE_END_DATE > sysdate
AND DPIH.LAST_MODIFIED < TO_DATE('03-02-2020 00:00:00','DD-MM-YYYY HH24:MI:SS')
AND DPIH.BASE_PRODUCT_INSTANCE_ID IS  NULL

MINUS

SELECT
 HDPI.GENERAL_1,
 HDPI.GENERAL_2,
 HDPI.GENERAL_3,
 HDPI.GENERAL_4,
 HDPI.GENERAL_5,
 HDPI.GENERAL_6,
 HDPI.GENERAL_7,
 HDPI.GENERAL_8,
 HDPI.GENERAL_9,
 HDPI.GENERAL_10
FROM SV_PROD.H3ATT_DWH_PROD_INST_HIST@SV9PCT01.IT.INTERNAL HDPI
JOIN SV_PROD.ACCOUNT@SV9PCT01.IT.INTERNAL AC ON HDPI.CUSTOMER_NODE_ID = AC.CUSTOMER_NODE_ID
     AND AC.ACCOUNT_NAME NOT IN ('PBA22643580','PBA60086806','PBA37052669','PBA17837525','PBA99398691')
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  AC.ACCOUNT_NAME = 'PBA'|| to_char (HPEA.X_BILL_SITE_ID) 
      AND HPEA.TASK_QUEUE_ID=1001003390    
WHERE 1=1
AND HDPI.BASE_PRODUCT_INSTANCE_ID IS  NULL

--)
--44381(GENERAL_6 DIFFS) 
--103 (GENERAL_5 Diffs Value 'UNKNOWN' in DWH) 
--457 (GENERAL_8 Diffs) 
--2720 (GENERAL_10 Diffs)
--4 (GENERAL_3 Diffs)

-------------------------------------------------------------------------------
declare
    type tabCol IS VARRAY(5) OF VARCHAR2(255);
    l_col tabcol;
    total int := 0;
    l_columns varchar(255) := '';
    l_count int :=0;
BEGIN
    l_col := tabcol('GENERAL_1','GENERAL_2','GENERAL_3');
    total := l_col.COUNT;
   
    FOR i in 1 .. total LOOP
        
        IF i = 1 THEN
          l_columns := l_col(i);      
        ELSIF i = total OR i > 1  THEN
          l_columns := l_columns ||','||l_col(i);
        END IF;
        
        l_count :=0;
        
        SELECT  count(*) INTO l_count FROM (
              SELECT DISTINCT l_columns
                FROM SV_BUS.PRODUCT_INSTANCE_HISTORY DPIH
                JOIN SV_PROD.H3ATT_DWH_PROD_INST_HIST@SV9PCT01.IT.INTERNAL SPIH ON DPIH.GENERAL_1 = SPIH.GENERAL_1 
                      AND DPIH.GENERAL_6 = SPIH.GENERAL_6 
              WHERE 1=1
                AND DPIH.PRODUCT_INSTANCE_STATUS_CODE <> 9
                AND DPIH.EFFECTIVE_END_DATE > sysdate
      
                MINUS
                
                SELECT DISTINCT l_columns
                FROM SV_PROD.H3ATT_DWH_PROD_INST_HIST@SV9PCT01.IT.INTERNAL 
        );
      
        DBMS_OUTPUT.put_line (l_columns || ' ---> Diff Count --> '|| l_count);
    END LOOP;
    
END;











 
