-----------------------CUSTOMER_NODE_HISTORY------------------------------------
SELECT
DCH.GENERAL_1
,DCH.TAX_CLASS_CODE
--,DCH.CREDIT_COMMENTS
,DCH.GENERAL_4
FROM SV_BUS.CUSTOMER_NODE_HISTORY DCH
JOIN SV_BUS.ACCOUNT ACC ON DCH.CUSTOMER_NODE_ID = ACC.CUSTOMER_NODE_ID
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  ACC.ACCOUNT_NAME = to_char (HPEA.X_BILL_SITE_ID)
      AND HPEA.TASK_QUEUE_ID=1001017526 and HPEA.ERROR_MESSAGE is null
WHERE 1=1
AND DCH.CUSTOMER_NODE_STATUS_CODE <> 9
AND DCH.EFFECTIVE_END_DATE > sysdate
AND DCH.LAST_MODIFIED < TO_DATE('03-02-2020 00:00:00','DD-MM-YYYY HH24:MI:SS')
and DCH.GENERAL_4 <> 'Standard'

 
MINUS
 
SELECT
 HDCN.GENERAL_1
 ,HDCN.TAX_CLASS_CODE
 --,HDCN.CREDIT_COMMENTS
 ,HDCN.GENERAL_5
 FROM SV_PROD.H3ATT_DWH_CN_HISTORY_V@SV9PCT01.IT.INTERNAL HDCN
JOIN SV_PROD.ACCOUNT@SV9PCT01.IT.INTERNAL AC ON HDCN.CUSTOMER_NODE_ID = AC.CUSTOMER_NODE_ID
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  AC.ACCOUNT_NAME = 'PBA'|| to_char (HPEA.X_BILL_SITE_ID)
      AND HPEA.TASK_QUEUE_ID=1001017526 and HPEA.ERROR_MESSAGE is null
WHERE 1=1

---------------------CUSTOMER_NODE_INV_FORMAT-----------------------------------

SELECT
CNH.GENERAL_1
--,DCNIF.GENERAL_4
,DCNIF.GENERAL_5
FROM SV_BUS.CUSTOMER_NODE_INV_FORMAT DCNIF
JOIN SV_BUS.ACCOUNT ACC ON DCNIF.CUSTOMER_NODE_ID = ACC.CUSTOMER_NODE_ID
JOIN SV_BUS.CUSTOMER_NODE_HISTORY CNH ON DCNIF.CUSTOMER_NODE_ID = CNH.CUSTOMER_NODE_ID
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  ACC.ACCOUNT_NAME = to_char (HPEA.X_BILL_SITE_ID)
      AND HPEA.TASK_QUEUE_ID=1001017526 and HPEA.ERROR_MESSAGE is null
WHERE 1=1
AND CNH.CUSTOMER_NODE_STATUS_CODE <> 9
AND CNH.EFFECTIVE_END_DATE > sysdate
AND CNH.LAST_MODIFIED < TO_DATE('03-02-2020 00:00:00','DD-MM-YYYY HH24:MI:SS')
AND DCNIF.EFFECTIVE_END_DATE > sysdate
AND DCNIF.LAST_MODIFIED < TO_DATE('03-02-2020 00:00:00','DD-MM-YYYY HH24:MI:SS')

MINUS
 
SELECT
DCN.GENERAL_1
--,HDCN.GENERAL_4
,HDCN.GENERAL_5
 FROM SV_PROD.H3ATT_DWH_CN_INV_FORMAT_V@SV9PCT01.IT.INTERNAL HDCN
JOIN SV_PROD.H3ATT_DWH_CN_HISTORY_V@SV9PCT01.IT.INTERNAL DCN ON HDCN.CUSTOMER_NODE_ID = DCN.CUSTOMER_NODE_ID
JOIN SV_PROD.ACCOUNT@SV9PCT01.IT.INTERNAL AC ON HDCN.CUSTOMER_NODE_ID = AC.CUSTOMER_NODE_ID
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  AC.ACCOUNT_NAME = 'PBA'|| to_char (HPEA.X_BILL_SITE_ID)
      AND HPEA.TASK_QUEUE_ID=1001017526 and HPEA.ERROR_MESSAGE is null
WHERE 1=1



-----------------------ACCOUNT------------------------------------
SELECT
DACC.ACCOUNT_NAME
FROM SV_BUS.ACCOUNT DACC
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  DACC.ACCOUNT_NAME = to_char (HPEA.X_BILL_SITE_ID)
      AND HPEA.TASK_QUEUE_ID=1001017464 and HPEA.ERROR_CODE is null
WHERE 1=1

MINUS

SELECT
AC.ACCOUNT_NAME
FROM SV_BUS.ACCOUNT AC
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON AC.ACCOUNT_NAME = to_char (HPEA.X_BILL_SITE_ID)
      AND HPEA.TASK_QUEUE_ID=1001017464 and HPEA.ERROR_CODE is null
WHERE 1=1

-----------------------CUSTOMER_NODE_TYPE------------------------------------
SELECT
DCH.CUSTOMER_NODE_TYPE_ID
FROM SV_BUS.CUSTOMER_NODE_HISTORY DCH
JOIN SV_BUS.ACCOUNT ACC ON DCH.CUSTOMER_NODE_ID = ACC.CUSTOMER_NODE_ID
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  ACC.ACCOUNT_NAME = to_char (HPEA.X_BILL_SITE_ID)
      AND HPEA.TASK_QUEUE_ID=1001017464 and HPEA.ERROR_CODE is null
WHERE 1=1
AND DCH.CUSTOMER_NODE_STATUS_CODE <> 9
AND DCH.EFFECTIVE_END_DATE > sysdate
AND DCH.LAST_MODIFIED < TO_DATE('03-02-2020 00:00:00','DD-MM-YYYY HH24:MI:SS')

 
MINUS
 
SELECT
 HDCN.CUSTOMER_NODE_TYPE_ID
 FROM SV_PROD.H3ATT_DWH_CN_HISTORY_V@SV9PCT01.IT.INTERNAL HDCN
JOIN SV_PROD.ACCOUNT@SV9PCT01.IT.INTERNAL AC ON HDCN.CUSTOMER_NODE_ID = AC.CUSTOMER_NODE_ID
JOIN SV_PROD.H3AT_PBE_EVENT_AUDIT@SV9PCT01.IT.INTERNAL HPEA ON  AC.ACCOUNT_NAME = 'PBA'|| to_char (HPEA.X_BILL_SITE_ID)
      AND HPEA.TASK_QUEUE_ID=1001017464 and HPEA.ERROR_CODE is null
WHERE 1=1
------------------------------
